stages:
- name: compile
  steps:
  - runScriptConfig:
      image: maven:3.6.1-jdk-11-slim
      shellScript: |-
        cd notes-service
        mvn package
        cd ..
  - runScriptConfig:
      image: trion/ng-cli:8.0.1
      shellScript: |-
        cd notes-ui
        ng build --prod
        cd ..
timeout: 60
