stages:
- name: compile backend
  steps:
  - runScriptConfig:
      image: maven:3.6.1-jdk-11-slim
      shellScript: |-
        cd notes-service
        mvn package
        cd ..
- name: build container
  steps:
  - publishImageConfig:
      dockerfilePath: ./notes-service/Dockerfile
      buildContext: .
      tag: daflockinger/poppynotes-backend:${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34685
- name: compile frontend
  steps:
  - runScriptConfig:
      image: trion/ng-cli:8.0.1
      shellScript: |-
        cd notes-ui
        ng build --prod
        cd ..
- name: build frontend container
  steps:
  - publishImageConfig:
      dockerfilePath: ./notes-ui/Dockerfile
      buildContext: .
      tag: daflockinger/poppynotes-frontend:${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34685
timeout: 60
