server:
  port: 8001
  
spring:
  data:
    cassandra:
      contact-points: 127.0.0.1
      port: 9042
      keyspace-name: poppynotes
      schema-action: CREATE_IF_NOT_EXISTS

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    
endpoints:
  shutdown:
    enabled: true    

management:
  security:
    enabled: false