server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    
endpoints:
  shutdown:
    enabled: true    

management:
  security:
    enabled: false