server:
  port: 8001
  
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: poppynotes
  jackson:
    date-format: com.flockinger.poppynotes.notesService.config.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
        
notes:
  security:
    allowed-origin: http://localhost:8001
    
    
#### Test Profile
---
spring: 
  profiles: test
  data:
    mongodb:
      host: localhost
      port: 27017
      database: testpoppynotes