server:
  port: 8001
  
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: poppynotes
  jackson:
    date-format: com.flockinger.poppynotes.notesService.config.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    
endpoints:
  shutdown:
    enabled: true    

management:
  security:
    enabled: false
    
    
#### Test Profile
---
spring: 
  profiles: test
  data:
    mongodb:
      host: localhost
      port: 0
      database: poppynotes