server:
  port: 8001
  
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: poppynotes
  jackson:
    date-format: com.flockinger.poppynotes.notesService.config.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
        
notes:
  security:
    allowed-origin: http://localhost:4200
  rate-limit:
    time-range-minutes: 1
    call-limit: 10
  settings:
    limits:
      max-title-length: 50
      max-content-length: 1000
      max-messages-per-user: 1000
    user-whitelist-enabled: true
    
    
#### Test Profile
---
spring: 
  profiles: test
  data:
    mongodb:
      host: localhost
      port: 27017
      database: testpoppynotes     
      