/**
 * PoppyNotes Note API
 * PoppyNotes Note API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface PinNote {
    /**
     * Boolean if the note should be set pinned or not
     */
    pinIt?: boolean;
    /**
     * Unique Identifier of the Note.
     */
    noteId?: string;
}
