server:
  port: 8888

eureka:
#  instance:
#    hostname: configuration-server
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configs
  profiles:
     active: native

     
management:
  security:
    enabled: false