server:
  port: 8001
  contextPath: /


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

management:
  security:
    enabled: false
    

############ put into config server later on !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!    
    
# Connection url for the database "netgloo_blog"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/poppyuser?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
# Username and password
    username: root
    password: root
# Keep the connection alive if idle for a long time (needed in production)
    testWhileIdle: true
    validationQuery: SELECT 1
# Show or not log for each sql query
  jpa: 
    database: mysql
#    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
# Hibernate ddl auto (create, create-drop, update): with "update" the database
# schema will be automatically updated accordingly to java entities found in
# the project
    hibernate:
      ddl-auto: validate
  jackson:
    date-format: com.flockinger.poppynotes.userService.config.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
        

settings:
  email:
    host: localhost
    port: 25
    user:
    password:
    
    
      
#logging:
#  level:
#    org:
#      hibernate:
#        tool:
#          hbm2ddl: DEBUG
#        SQL: DEBUG   
#        type: TRACE  
###      
      
      
#### Test Profile
---
spring: 
  profiles: test
  datasource:
    url: jdbc:mysql://localhost:3306/testpoppyuser?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
flyway:
  baseline-on-migrate: true